name: todo_app
description: Данное приложение покажет сколько времени осталось до нужного вам события.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  flutter_svg: ^2.0.5
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  intl: ^0.17.0
  package_info_plus: ^3.0.3
  jiffy: ^5.0.0
  flutter_local_notifications: ^14.0.0+1
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900